### PR TITLE
Auto format

### PR DESCRIPTION
**Pull request by owickstrom**
Runs auto-formatting after pushes to the `main` branch.

### CODE REVIEW

**Comment by liamoc** [comment]
This is fine, but is there a diff of the current codebase?

**Comment by owickstrom** [comment]
> This is fine, but is there a diff of the current codebase?

I'm afraid not a clean diff, I did some formatting before. :disappointed:

**Comment by owickstrom** [comment]
I was annoyed today with lists having the commas at the end of lines. I might try `fourmolu` before merging this.

**Comment by owickstrom** [comment]
Couldn't get it to work, so merging this. Let's revisit if we have problems with it.

**Pull request merged**
